/*
SQL script to copy DESCRIPTION, LOGO URL and THUMBNAIL URL to new CONFTEXT table.
For H2 database.
The columns above will be deprecated.
*/

CREATE TABLE IF NOT EXISTS CONFTEXT(
  UUID varchar(255) NOT NULL DEFAULT RANDOM_UUID(),
  ctType varchar(255) NOT NULL,
  TEXT varchar(255),
  CONFERENCE_UUID varchar(255) NOT NULL
);

INSERT INTO CONFTEXT (CTTYPE, "TEXT", CONFERENCE_UUID)
  SELECT 'description', DESCRIPTION, UUID FROM CONFERENCE
  WHERE DESCRIPTION IS NOT NULL AND NOT EXISTS (
      SELECT CTTYPE, CONFERENCE_UUID FROM CONFTEXT
      WHERE CONFTEXT.CONFERENCE_UUID = CONFERENCE.UUID
            AND CONFTEXT.CTTYPE = 'description'
  );

INSERT INTO CONFTEXT (CTTYPE, TEXT, CONFERENCE_UUID)
  SELECT 'logo', LOGO, UUID FROM CONFERENCE
  WHERE LOGO IS NOT NULL AND NOT EXISTS (
      SELECT CTTYPE, CONFERENCE_UUID FROM CONFTEXT
      WHERE CONFTEXT.CONFERENCE_UUID = CONFERENCE.UUID
            AND CONFTEXT.CTTYPE = 'logo'
  );

INSERT INTO CONFTEXT (CTTYPE, TEXT, CONFERENCE_UUID)
  SELECT 'thumbnail', THUMBNAIL, UUID FROM CONFERENCE
  WHERE THUMBNAIL IS NOT NULL AND NOT EXISTS (
      SELECT CTTYPE, CONFERENCE_UUID FROM CONFTEXT
      WHERE CONFTEXT.CONFERENCE_UUID = CONFERENCE.UUID
            AND CONFTEXT.CTTYPE = 'thumbnail'
  );

ALTER TABLE CONFERENCE
DROP COLUMN IF EXISTS DESCRIPTION;
ALTER TABLE CONFERENCE
DROP COLUMN IF EXISTS LOGO;
ALTER TABLE CONFERENCE
DROP COLUMN IF EXISTS THUMBNAIL;

SELECT * FROM CONFERENCE;
SELECT * FROM CONFTEXT;