sudo: required
dist: trusty
language: scala
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt
jdk:
  - oraclejdk8
env:
  - ACTIVATOR_VERSION=1.3.7
before_script:
  - wget https://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - unzip -q typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - unset SBT_OPTS JVM_OPTS
script: activator-${ACTIVATOR_VERSION}-minimal/activator test
notifications:
  email: false
